name: Publish Docker Image to DockerHub

on:
  push:
    branches: [main]

jobs:
  publish-cloud-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          file: cloud-job/Dockerfile
          push: true
          tags: |
            backcast/cloud-job:latest
            backcast/cloud-job:${{ github.sha }}

  publish-cloud-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: cloud-run
          file: cloud-run/Dockerfile
          push: true
          tags: |
            backcast/cloud-run:latest
            backcast/cloud-run:${{ github.sha }}
